### ISSUE TITLE
Multiple databases support?

### ISSUE THREAD

**Issue by pendolf** [doismellburning/django12factor#33]
Can you add support for [Django Multiple databases] (https://docs.djangoproject.com/en/1.7/topics/db/multi-db/)?

**Comment by doismellburning** [comment]
Sure :) Any ideas how you'd like the interface to look?

I'm thinking something like:

* `DATABASE_URL` gets parsed to become `settings.DATABASES['default']`
* `FOO_DATABASE_URL` becomes `settings.DATABASES['foo']`

This:

* Doesn't change existing behaviour
* Means adding a database is as simple as adding an environment variable

Potential disadvantages:

* Only makes lower-case `DATABASES`
    * This doesn't seem particularly unconventional though based on Django docs
* Doesn't lend itself to sorted display
    * `TEST_DATABASE_URL` does feel more natural than `DATABASE_URL_TEST` though

How does that sound?

**Comment by pendolf** [comment]
Sounds good! 
So for example, if i have this settings before: 
```
DATABASES = {
    'default': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db1'),
    'db2': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db2'),
    'db3': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db3'),
}
```
I need to export:
```
export default='mysql://user:password@10.10.10.11:3306/db1' 
export db2='mysql://user:password@10.10.10.12:3306/db2' 
export db2='mysql://user:password@10.10.10.13:3306/db3' 
```
and use this code in settings?
```
import django12factor
d12f = django12factor.factorise()
DATABASE_URL = d12f['default']
DB2_DATABASE_URL = d12f['db2']
DB3_DATABASE_URL = d12f['db3']
```

**Comment by doismellburning** [comment]
Not quite - your settings example is slightly backwards.

If you start with the below:

```
DATABASES = {
    'default': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db1'),
    'db2': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db2'),
    'db3': dj_database_url.parse('mysql://user:password@10.10.10.10:3306/db3'),
}
```

you can then:

```
export DATABASE_URL="mysql://user:password@10.10.10.10:3306/db1"
export DB2_DATABASE_URL="mysql://user:password@10.10.10.10:3306/db2"
export DB3_DATABASE_URL="mysql://user:password@10.10.10.10:3306/db3"
```

and in your `settings.py` just have:

```
import django12factor
d12f = django12factor.factorise()
DATABASES = d12f['DATABASES']
```

Does that make sense, and if so, does it feel sensible/convenient?

**Comment by pendolf** [comment]
Yes, all clear.
