### ISSUE TITLE
Error if email-url password contains /

### ISSUE THREAD

**Issue by uber1geek** [doismellburning/django12factor#76]
If the password contains special characters such as ? or /, the following exception is raised (here I tried to use "foo/bar" as a password):

`ValueError: invalid literal for int() with base 10:`

**Comment by jdelic** [comment]
I can see from [dj-email-url#13](https://github.com/migonzalvar/dj-email-url/issues/13) that you already realized that django12factor does not parse the email URL itself.

That said, it's a URL. So, though that's not immediately obvious from the documentation, you can (and must) use URL encoding for characters that have special meaning in URLs:

```python
>>> import urllib, dj_email_url
>>> urllib.parse.quote("/?", safe="")
'%2F%3F'
>>> dj_email_url.parse("smtp://test:blah%2F%3F4@smtp.example.com:465/")
{'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
 'EMAIL_FILE_PATH': '',
 'EMAIL_HOST': 'smtp.example.com',
 'EMAIL_HOST_PASSWORD': 'blah/?4',
 'EMAIL_HOST_USER': 'test',
 'EMAIL_PORT': 465,
 'EMAIL_USE_SSL': False,
 'EMAIL_USE_TLS': False}
```

I hope this helps. Please close the issues you have opened if it does.

**Comment by jdelic** [comment]
I assume the lack of updates means that you have resolved your issue.
